import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider as NextThemesProvider } from "next-themes";

import Provider from "./Provider";
import ConvexClientProvider from "./ConvexProviderWithClerk";
import { ClerkProvider } from "@clerk/nextjs";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import Header from "@/components/Header";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider>
          <ConvexClientProvider>
            <NextThemesProvider attribute="class" defaultTheme="system" enableSystem>
              <SidebarProvider defaultOpen={false}>
                <AppSidebar />
                <main className="w-full">
                  <Header />
                  {children}
                </main>
              </SidebarProvider>
            </NextThemesProvider>
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
